select * from customer limit 20

--1.what is the total revenue generated by male vs female cutomer
select gender, sum(purchase_amount) as revenue
from  customer
group by gender

--2.which customer used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3.which are the top 5 products with the highest average review rating
select item_purchased, ROUND(AVG(review_rating::numeric),2)as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4.compare the average purchase amount between standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5.DO subscibed customers spend more? compare average spend and total revenue between between subscribe and non-subscibers
select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--6.which 5 products have the highest percetage of purchase with dicount applied
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--7.Segment customer into New, Returning, and loyal based on their total
-- number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
CASE  
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	WH
)